pipeline:
  name: test
  identifier: test
  projectIdentifier: java
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1744654512528
        repoName: https://github.com/pvsriram99/Boardgame.git
        build: <+input>
  stages:
    - stage:
        name: comple
        identifier: comple
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: compile
                  identifier: compile
                  spec:
                    shell: Sh
                    command: mvn compile
